Added a next prop named alternate text to receive alternate text for …
activist-org/activist pull request #156
Opened 2023-05-19 10:18 UTC by Gauravvpnd

…button

<!---
Thank you for your pull request! 🚀

If you're not already a member of our public Matrix community, please consider joining via the following link:
https://matrix.to/#/#activist_community:matrix.org

It'd be great to have you!

2023-05-19 18:15 UTC, andrewtavis requested changes
Hey @Gauravvpnd! I'm realizing I didn't explain this as well as I should have. Specifically we're not looking for an alternate text for the button, but rather an alternate text that would be read by a screen reader for someone who's visibly impaired. I'll go into the code and explicitly describe what should happen :)

2023-05-19 18:16 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
> +const buttonText = computed(() => alternateText || $t(label));
We don't need this line as the button's text should be `t$(label)` :)

2023-05-19 18:16 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
> +  alternateText: string; // New prop for alternate text
This is great, but we don't need the comment saying it's "new".

2023-05-19 18:16 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
> +    {{ buttonText }}
This should be reverted back to `$t(label)`.

2023-05-19 18:17 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
> +    {{ buttonText }}
This should be reverted back to `$t(label)`.

2023-05-19 18:18 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
>    <a
This `<a>` tag should be given an `aria-label` attribute that has `alternateText` assigned to it 😊

2023-05-19 18:18 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
>    <NuxtLink
This `<NuxtLink>` tag should be given an `aria-label` attribute that has `alternateText` assigned to it 😊

2023-05-19 18:20 UTC, andrewtavis commented
A short article from the World Wide Web Consortium can be seen here: https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA8

Let me know on the above! As soon as we have the above changes I'd be happy to merge, and then from there you can let me know if you have interest in writing alternate texts for some of the `LabeledBtn` components in the code base :)

2023-05-25 20:28 UTC, andrewtavis commented
Hey @Gauravvpnd 👋 Checking in with you to see how you're doing with all this. Very happy to assist if there's something I can do to help. Just let me know :)

2023-06-08 07:26 UTC, andrewtavis commented
@Gauravvpnd, checking in again to see how you're doing :) If you're unsure about the changes we could also do a quick call or I could explain things in more detail 😊 Hope you're well!

2023-06-08 07:33 UTC, Gauravvpnd commented
> changes

Hey,I'm not able to get what are the specific changes need to do it will be helpful if you will tell me a little on what to do. I am not able to get your point.

2023-06-08 07:46 UTC, andrewtavis commented
Something else that I'm noticing is that you don't seem to have your email for GitHub set up properly. The [email that you use for GitHub](https://github.com/settings/emails) should be the same that you have for `git config --global user.email` or locally for the repo :)

2023-06-08 16:19 UTC, andrewtavis commented
I’d again be happy to discuss all this over a call, @Gauravvpnd :) Just let me know what your time zone is and we can figure out a time that would work for both of us.

2023-06-26 17:11 UTC, andrewtavis commented
Hi @Gauravvpnd 👋 I’m going to close this PR now as there are conflicts that are unresolved. There’s some interest from people to maybe work on this, and I might need to assign them. Would be happy to work with you on another issue in the future! Please be in touch and thanks for your interest in activist :)

2023-06-26 17:11 UTC, closed without merging