Second
activist-org/activist pull request #162
Opened 2023-05-21 05:39 UTC by trishas95

### Contributor checklist

- [ ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

### Related issue

- #ISSUE_NUMBER

2023-05-21 17:07 UTC, andrewtavis commented on frontend/i18n/en-US.json
> +  "wikimedia-rs-logo-label": "Link to the website of Wikimedia Serbia",
Could you add a period here for consistency?

2023-05-21 17:07 UTC, andrewtavis commented on frontend/i18n/en-US.json
> +  "impacthub-belgrade-logo-label": "Link to the website of Impact Hub Belgrade"
A period here too would be great :)

2023-05-21 17:09 UTC, andrewtavis requested changes
Thanks @trishas95! This is basically done. The last thing that's needed is that you need to add a `:` before the aria labels so that the translated values can be read in rather than a string. I'm realizing I should have explained this better. I just pulled in your branch and the correct way of doing this would be:

```
:aria-label="$t('wikimedia-de-logo-label')"
```

Once the fixes I mentioned about adding some periods in the descriptions and changing the `aria-label` attributes is done we'll be good to merge!

2023-05-21 18:35 UTC, trishas95 commented
Hello @andrewtavis, I made the changes you've mentioned above. This is one my first few PRs, looking forward to learning more! :)

2023-05-21 18:39 UTC, andrewtavis commented
Thank you, @trishas95! Happy to help you learn more :) I’ll do the final review tomorrow 😊

2023-05-23 22:31 UTC, andrewtavis commented
Hey @trishas95! Have had a few busy days and didn't get a moment to do the final check of this till now. I'm realizing there's still one very small issue here 🙃 You need the elements within the `t()` to be in single quotes, so `t('wikimedia-de-logo-label')`. Sorry I didn't mention this part more explicitly when I discussed the `:` above. As of now what we have there is `translate(wikimedia - de - logo - label)` like it's subtraction, but what we want is `translate('the-string-in-kebab-case')` that will then feed the key into translation and provide the appropriate value :)

2023-05-25 18:55 UTC, trishas95 commented
@andrewtavis I made the changes :D

2023-05-25 19:04 UTC, merged