feature: added leftIcon and RightIcon to LabeledBtn component
activist-org/activist pull request #175
Opened 2023-05-26 22:26 UTC by tarunsamanta2k20

### Contributor checklist

- [ ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description
Add icon properties to LabeledBtn component #173

I have searched [open and closed feature requests](https://github.com/activist-org/activist/issues?q=is%3Aissue+label%3Afeature)
 I agree to follow activist's [Code of Conduct](https://github.com/activist-org/activist/blob/main/.github/CODE_OF_CONDUCT.md)
Description
This issue would be to add two properties and their implementations to the [frontend/components/LabeledBtn.vue](https://github.com/activist-org/activist/blob/main/frontend/components/LabeledBtn.vue) component. We want both properties to be optional, with the first being leftIcon and the second being rightIcon. Each takes a string and would thus allow for identifies of icons to be passed to <Icon> components in the name property.

An example of a LabeledBtn with leftIcon as bi:pencil-square would be:

Mode=Dark, Mobile=True, Icon=Edit, Hover=False

Contribution
This would be a great first issue for someone who wants some experience with Vue/Nuxt/Tailwind, but is of course open to current contributors :) Happy to discuss, support, or work on it myself if no one has interest blush
### Related issue

- #ISSUE_NUMBER
- #173

2023-05-29 22:25 UTC, andrewtavis commented on frontend/components/LabeledBtn.vue
> +  rightIcon?: string
This here needs a semicolon :)

2023-05-29 22:44 UTC, andrewtavis requested changes
Hey @tarunsamanta2k20 👋 Appreciate the commit here and also the quick fix :) A part of #173 is also adding the icons to the button itself such that when one of the properties that you created is passed that that the icon will be added. Within the `<template>` we need `v-if` statements within `<Icon>` components that check if something has been passed to the properties. The code for `leftIcon` would be something along the following:

```vue
<Icon v-if="leftIcon" :name="leftIcon">
``` 

This code would come before the `<a>` tag and a similar block would follow the `<NuxtLink>` tag. Along with this we now also have multiple items within this button, not just a word. In those regards we need to make the button itself a flex container so that we can center the items within it. I'm not sure how exactly to do this, but hopefully a `<div>` tag around the words and the icon components would work with the `div` tag having the following `class="flex items-center"` (this is a Tailwind CSS class that will make sure things are centered vertically).

Let me know if you need more explanations on this :) Happy to give you more directing. Just want to make sure that you can try to work out how to use everything yourself 😊

2023-05-29 23:53 UTC, tarunsamanta2k20 commented
> Hey @tarunsamanta2k20 👋 Appreciate the commit here and also the quick fix :) A part of #173 is also adding the icons to the button itself such that when one of the properties that you created is passed that that the icon will be added. Within the `<template>` we need `v-if` statements within `<Icon>` components that check if something has been passed to the properties. The code for `leftIcon` would be something along the following:
> 
> ```
> <Icon v-if="leftIcon" :name="leftIcon">
> ```
> 
> This code would come before the `<a>` tag and a similar block would follow the `<NuxtLink>` tag. Along with this we now also have multiple items within this button, not just a word. In those regards we need to make the button itself a flex container so that we can center the items within it. I'm not sure how exactly to do this, but hopefully a `<div>` tag around the words and the icon components would work with the `div` tag having the following `class="flex items-center"` (this is a Tailwind CSS class that will make sure things are centered vertically).
> 
> Let me know if you need more explanations on this :) Happy to give you more directing. Just want to make sure that you can try to work out how to use everything yourself 😊
Will make changes

> Hey @tarunsamanta2k20 wave Appreciate the commit here and also the quick fix :) A part of #173 is also adding the icons to the button itself such that when one of the properties that you created is passed that that the icon will be added. Within the `<template>` we need `v-if` statements within `<Icon>` components that check if something has been passed to the properties. The code for `leftIcon` would be something along the following:
> 
> ```
> <Icon v-if="leftIcon" :name="leftIcon">
> ```
> 
> This code would come before the `<a>` tag and a similar block would follow the `<NuxtLink>` tag. Along with this we now also have multiple items within this button, not just a word. In those regards we need to make the button itself a flex container so that we can center the items within it. I'm not sure how exactly to do this, but hopefully a `<div>` tag around the words and the icon components would work with the `div` tag having the following `class="flex items-center"` (this is a Tailwind CSS class that will make sure things are centered vertically).
> 
> Let me know if you need more explanations on this :) Happy to give you more directing. Just want to make sure that you can try to work out how to use everything yourself blush

Will make changes by sometime.

2023-05-29 23:53 UTC, tarunsamanta2k20 commented
> Hey @tarunsamanta2k20 👋 Appreciate the commit here and also the quick fix :) A part of #173 is also adding the icons to the button itself such that when one of the properties that you created is passed that that the icon will be added. Within the `<template>` we need `v-if` statements within `<Icon>` components that check if something has been passed to the properties. The code for `leftIcon` would be something along the following:
> 
> ```
> <Icon v-if="leftIcon" :name="leftIcon">
> ```
> 
> This code would come before the `<a>` tag and a similar block would follow the `<NuxtLink>` tag. Along with this we now also have multiple items within this button, not just a word. In those regards we need to make the button itself a flex container so that we can center the items within it. I'm not sure how exactly to do this, but hopefully a `<div>` tag around the words and the icon components would work with the `div` tag having the following `class="flex items-center"` (this is a Tailwind CSS class that will make sure things are centered vertically).
> 
> Let me know if you need more explanations on this :) Happy to give you more directing. Just want to make sure that you can try to work out how to use everything yourself 😊
Will make changes

> Hey @tarunsamanta2k20 wave Appreciate the commit here and also the quick fix :) A part of #173 is also adding the icons to the button itself such that when one of the properties that you created is passed that that the icon will be added. Within the `<template>` we need `v-if` statements within `<Icon>` components that check if something has been passed to the properties. The code for `leftIcon` would be something along the following:
> 
> ```
> <Icon v-if="leftIcon" :name="leftIcon">
> ```
> 
> This code would come before the `<a>` tag and a similar block would follow the `<NuxtLink>` tag. Along with this we now also have multiple items within this button, not just a word. In those regards we need to make the button itself a flex container so that we can center the items within it. I'm not sure how exactly to do this, but hopefully a `<div>` tag around the words and the icon components would work with the `div` tag having the following `class="flex items-center"` (this is a Tailwind CSS class that will make sure things are centered vertically).
> 
> Let me know if you need more explanations on this :) Happy to give you more directing. Just want to make sure that you can try to work out how to use everything yourself blush

Will make changes by sometime.

2023-05-30 07:15 UTC, andrewtavis commented
Thank you, @tarunsamanta2k20! Again let me know if there’s anything I can do to help :)

2023-05-30 08:26 UTC, tarunsamanta2k20 commented
> Thank you, @tarunsamanta2k20! Again let me know if there’s anything I can do to help :)

@an

> Thank you, @tarunsamanta2k20! Again let me know if there’s anything I can do to help :)

2023-05-30 08:27 UTC, tarunsamanta2k20 commented
> Thank you, @tarunsamanta2k20! Again let me know if there’s anything I can do to help :)

@andrewtavis which file should I change?

Iconactivist or IconEvent?

2023-05-30 08:35 UTC, tarunsamanta2k20 commented
@andrewtavis let me check.

2023-05-30 08:37 UTC, tarunsamanta2k20 commented
@andrewtavis sorry i wrongly closed it, reopen this pull please. i wrongly clicked on closed with commits.

2023-05-31 12:26 UTC, tarunsamanta2k20 commented
@tarunsamanta2k20 can we do a pairing for this issue?

2023-06-02 19:33 UTC, tarunsamanta2k20 commented
Okay, let me know over here.

2023-06-03 13:30 UTC, andrewtavis commented
What’s your time zone, @tarunsamanta2k20? Just checking so I know when to suggest :)

2023-06-03 13:37 UTC, tarunsamanta2k20 commented
> What’s your time zone, @tarunsamanta2k20? Just checking so I know when to suggest :)

GMT (+5:30)

2023-06-03 14:03 UTC, andrewtavis commented
Thank you! Will check back in, but maybe we could do Tuesday after work for me like [16:00 UTC](https://zonestamp.toolforge.org/1686067220)? Would that work?

2023-06-04 23:29 UTC, tarunsamanta2k20 commented
> Thank you! Will check back in, but maybe we could do Tuesday after work for me lik

2023-06-04 23:30 UTC, tarunsamanta2k20 commented
> Thank you! Will check back in, but maybe we could do Tuesday after work for me like [16:00 UTC](https://zonestamp.toolforge.org/1686067220)? Would that work?

Sure, will work for me as well.

2023-06-06 07:21 UTC, andrewtavis commented
Also, @tarunsamanta2k20, let me know if you've been able to set up the development environment as described in [the readme](https://github.com/activist-org/activist#environment-setup-) :) Would be good if we could just jump in later today 😊

2023-06-06 11:10 UTC, tarunsamanta2k20 commented
> Also, @tarunsamanta2k20, let me know if you've been able to set up the development environment as described in [the readme](https://github.com/activist-org/activist#environment-setup-) :) Would be good if we could just jump in later today blush

No, I haven't completed it yet. Will do by today. Also, can we schedule this meeting for tomorrow at the same time? Having some issues on my side.

2023-06-06 12:32 UTC, andrewtavis commented
No stress. Would an hour earlier or 30 minutes earlier be ok? I have a dinner with a friend scheduled already.

2023-06-07 13:45 UTC, andrewtavis commented
Hey @tarunsamanta2k20, as we haven’t confirmed I’m not going to be able to make it. Maybe sometime early next week? Let me know if you have issues setting up the development environment! :)

2023-06-07 13:47 UTC, tarunsamanta2k20 commented
> Hey @tarunsamanta2k20, as we haven’t confirmed I’m not going to be able to make it. Maybe sometime early next week? Let me know if you have issues setting up the development environment! :)

Sure, next week will be fine for both of us. Also let me know in advance 1 or 2 dats before.

2023-06-07 14:04 UTC, andrewtavis commented
Ok, let’s plan for Monday next week at 16:00 UTC.

2023-06-12 06:45 UTC, andrewtavis commented
Hey again, @tarunsamanta2k20 :) Are we still on for this evening? And let me know if you have any questions about the dev environment!

2023-06-12 08:06 UTC, tarunsamanta2k20 commented
> Hey again, @tarunsamanta2k20 :) Are we still on for this evening? And let me know if you have any questions about the dev environment!

At 11:15 p.m IST

2023-06-12 11:57 UTC, andrewtavis commented
Could we do a bit earlier? Say 10:30 IST?

2023-06-12 15:23 UTC, tarunsamanta2k20 commented
> Could we do a bit earlier? Say 10:30 IST?

I'm busy. Can't do

2023-06-12 15:36 UTC, andrewtavis commented
Ok, let’s shoot for 11:15 IST. Where is the call happening? Can you send me an invite to the email in my GitHub profile, or send along your email and I’ll set something up?

2023-06-12 18:01 UTC, andrewtavis approved these changes
Thanks for the call and the changes, @tarunsamanta2k20! As I said, let's be in touch on if there's another issue you want to work on :) There will be plenty of new ones in the coming weeks 🙃

2023-06-12 18:01 UTC, merged