FAQ Link Accessibility
activist-org/activist pull request #92
Opened 2023-04-03 23:31 UTC by rufaida99-k

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

The FAQ page had a link that was not readable according to the WCAG guidelines so I added some code to change that. 
The files I changed were:
1. frontend/assets/css/tailwind.css
2. frontend/pages/help/faq.vue

Showing a before after picture below to show the difference:
BEFORE:
![image](https://user-images.githubusercontent.com/112827402/229648534-cb99fed7-dc31-4b00-8fe5-a776818c5c96.png)

AFTER:
![image](https://user-images.githubusercontent.com/112827402/229648576-4aadbf10-05c8-4965-a625-dfd36e9ed4cd.png)

### Related issue
#91

2023-04-04 23:16 UTC, andrewtavis commented on frontend/pages/help/faq.vue
> +        class="link-text"
This should maintain `focus-brand` :)

2023-04-04 23:24 UTC, andrewtavis requested changes
Thanks, @rufaida99-k! 🙏🚀 Just have some minor questions on this:

- I don't really understand what's going on with `backend/manage.py`. Can you remove the change to that? It looks like the contents are being deleted 🤔
- Could you go through and replace the link classes on other instances of external links like on the supporters pages, about page and others? I think searching for `hover:underline` should give you most instances of external links 😊
- As I said in [a comment](https://github.com/activist-org/activist/pull/92/files#r1157854912), `focus-brand` should be maintained on the class for external links :) :) The end class should be `"focus-brand link-text"`

Happy to merge when these minor changes go through! Thanks again!

2023-04-05 00:34 UTC, rufaida99-k commented
@andrewtavis got it, making the changes on a new branch. 
I didn't realize the manage.py files even got changed, will make sure that doesn't happen again. 
I'll be sure to make the change "focus-brand link-text" instead of "link-text".
Just one quick follow up:
There are elements like "items-center text-light-cta-orange dark:text-dark-cta-orange hover:underline focus-brand" when I search for "hover:underline", do I maintain the leading "items-center" or replace it altogether with  "focus-brand link-text"?
Also thank you so much for the feedback and your patience :)

2023-04-05 06:22 UTC, andrewtavis commented
In the future you can just send the commits to this branch, @rufaida99-k 😊 And no need to thank me for feedback and patience! Thank you for your contributions! Will close this one and check the other :)

2023-04-05 06:22 UTC, closed without merging