feat: create privacy policy
activist-org/activist pull request #95
Opened 2023-04-11 05:25 UTC by wldeh

### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
  
  

---

### Description

This PR adds a detailed privacy policy at /legal/privacy-policy UR

### Related issue

- #44

2023-04-11 06:52 UTC, andrewtavis commented
Thanks for your work here as well, @wldeh! I’ll check all this when you’ve finalized them :)

2023-04-12 06:12 UTC, wldeh commented
> Thanks for your work here as well, @wldeh! I’ll check all this when you’ve finalized them :)

For sure! Yeah I'm not sure if there were any plans to set up a Figma page for this project. Regarding the policy contents I've committed here, there's definitely room for improvement. I would appreciate any guidance or direction you may have. Looking forward to your feedback!

2023-04-12 06:36 UTC, andrewtavis commented
Thanks, @wldeh! There were no Figma files for this page specifically, but I'll likely style it the same as the about page once the text contents are merged. We can also do an actual `PRIVACY.txt` file for this as well like in Scribe :) I'll check this later!

2023-04-13 09:01 UTC, wldeh commented
> Thanks, @wldeh! There were no Figma files for this page specifically, but I'll likely style it the same as the about page once the text contents are merged. We can also do an actual `PRIVACY.txt` file for this as well like in Scribe :) I'll check this later!

Appreciate the update @andrewtavis! Are we planning to put the PRIVACY.txt file in the root directory? I can integrate it here soon after taking a closer look at the Scribe implementation.

2023-04-13 09:06 UTC, andrewtavis commented
Hey @wldeh 👋 Yes, the `PRIVACY.txt` file would go in the project root. If you have interest in integrating it, then please do 😊 I’m very focused on the v2.2.0 release of Scribe at the moment, but my priority will switch hard back to activist next week :) Really grateful to get some help here!

2023-04-13 09:23 UTC, wldeh commented
> Hey @wldeh 👋 Yes, the `PRIVACY.txt` file would go in the project root. If you have interest in integrating it, then please do 😊 I’m very focused on the v2.2.0 release of Scribe at the moment, but my priority will switch hard back to activist next week :) Really grateful to get some help here!

Completely understood. Alright yeah I'll definitely look to have a polished setup here by next week. Thanks again!

2023-04-13 13:33 UTC, andrewtavis commented
Thank you!! 😊

2023-04-14 07:42 UTC, andrewtavis commented on frontend/pages/legal/privacy-policy.vue
> +            By using Activist.org, you agree to the provisions of this Privacy
activist is always lower case 🙃

2023-04-14 07:44 UTC, andrewtavis commented on frontend/pages/legal/privacy-policy.vue
> +            personal information. Activist.org is dedicated to ensuring the
Same here 🙃

2023-04-14 07:46 UTC, andrewtavis commented on frontend/pages/legal/privacy-policy.vue
> +            users to contribute to Activist.org and participate in discussions
And one below :)

2023-04-14 07:47 UTC, andrewtavis commented on frontend/pages/legal/privacy-policy.vue
> +            other means. By continuing to use Activist.org after any changes are
Last one!!! 😊

2023-04-14 07:50 UTC, andrewtavis requested changes
This reads really well, @wldeh! I'll go through and do some edits on my side, but from my end we can just change the `Activist.org` mentions to `activist.org`. I can then go through and format the page like https://activist.org/en/about/. 

You're also welcome to commit an updated version as a `PRIVACY.txt` file! 

Thanks again, @wldeh! 🚀 Super helpful 😊

2023-04-17 07:04 UTC, wldeh commented
> Alsooo, if you're a Matrix user, feel free to join us in the [public chat](https://matrix.to/#/#activist_community:matrix.org) so we can connect on future issues 😊

Thank you for the link! I'm actually not a Matrix user yet, but I'm interested in learning more about it. Going to setup an account here shortly.

2023-04-17 07:08 UTC, andrewtavis commented
Great, @wldeh! I'm almosttt done with the Scribe release, btw 😊 So much to do for this one as the data process changed dramatically. Will get to this soon after :)

Feel free to send along the changes that I mentioned [here](https://github.com/activist-org/activist/pull/95#pullrequestreview-1384842984) and we can merge directly :) :)

2023-04-17 07:15 UTC, wldeh commented
> This reads really well, @wldeh! I'll go through and do some edits on my side, but from my end we can just change the `Activist.org` mentions to `activist.org`. I can then go through and format the page like https://activist.org/en/about/.
> 
> You're also welcome to commit an updated version as a `PRIVACY.txt` file! We can then merge after that :)
> 
> Thanks again, @wldeh! 🚀 Super helpful 😊



> This reads really well, @wldeh! I'll go through and do some edits on my side, but from my end we can just change the `Activist.org` mentions to `activist.org`. I can then go through and format the page like https://activist.org/en/about/.
> 
> You're also welcome to commit an updated version as a `PRIVACY.txt` file! We can then merge after that :)
> 
> Thanks again, @wldeh! 🚀 Super helpful 😊

Thank you for your feedback, @andrewtavis! I fixed all the Activist.org issues here and created a PRIVACY.txt file in the root directory. Ill try to push a commit here in the next day that replicates the 

> Great, @wldeh! I'm almosttt done with the Scribe release, btw 😊 So much to do for this one as the data process changed dramatically. Will get to this soon after :)
> 
> Feel free to send along the changes that I mentioned [here](https://github.com/activist-org/activist/pull/95#pullrequestreview-1384842984) and we can merge directly :) :)

Alright yeah I fixed all the Activist.org issues here and created a PRIVACY.txt file in the root directory. Ill try to push a commit here in the next day that replicates the about page as well. Thanks again for your feedback, @andrewtavis and apologies for the delay!

2023-04-18 08:18 UTC, wldeh commented
> No delay whatsoever, @wldeh! The stuff about formatting the page and everything is definitely beyond what I'd expect 😊👏 Thank you! What you can do is just use the about pages icon and everything, so just copy that page and replace the content with the policy. I'll then go in and replace the activist icon with something like a shield or something like we have for Scribe :)

Perfect Alright. Just pushed these changes. Things are not looking the cleanest but feel free to review when you can.

2023-04-23 09:14 UTC, andrewtavis approved these changes
Thank you, @wldeh! Sorry for getting to this a bit late :) Has been a crazy busy week for me, but I'm shifting focus back to activist going forward 😊 I'll do some minor edits to the text and switch over the privacy policy icon to something to a shield with a checkmark so we're telling people they're safe.

Looking forward to further collaborations!

2023-04-23 09:15 UTC, merged

2023-04-24 07:25 UTC, wldeh commented
> Thank you, @wldeh! Sorry for getting to this a bit late :) Has been a crazy busy week for me, but I'm shifting focus back to activist going forward 😊 I'll do some minor edits to the text and switch over the privacy policy icon to something to a shield with a checkmark so we're telling people they're safe.
> 
> Looking forward to further collaborations!

Great to hear Andrew and no worries at all! The checkmark definitely makes more sense. Happy to say I am a fan of this projects vision and definitely planning on making some more significant contributions here moving forward. Cheers!

2023-04-24 07:41 UTC, andrewtavis commented
Wonderful to hear 😊😊